### ISSUE TITLE
Investigate: img2img prompt_strength=1.0 doesn't seem to destroy the init image completely

### ISSUE THREAD

**Issue by andreasjansson** [replicate/cog-stable-diffusion#21]
When `prompt_strength=1`, SD should behave as though there were no init image. However, that doesn't seem to be the case as has been reported on Discord: https://discord.com/channels/775512803439280149/881521351381385216/1019910914692108309

We should investigate why this happens and fix it!

**Comment by Keep-up-sharma** [comment]
https://github.com/replicate/cog-stable-diffusion/pull/22
Created a pull request

**Comment by ishowta** [comment]
Maybe `strength` is the right key.
https://github.com/huggingface/diffusers/blob/a4d5b59f132126c06c1a6b1f266ee44c70440cce/src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_img2img.py#L55
