### ISSUE TITLE
Always outputing 1 image when selecting 4

### ISSUE THREAD

**Issue by andersalm** [replicate/cog-stable-diffusion#39]
I know it says "Number of images to output. NSFW filter in enabled, so you may get fewer outputs than requested if flagged" but I'm getting 1 image only consistently, always 3 images flagged as NSFW. Even with prompts such as "all green" checkboard pattern".

When I do the default prompt "multicolor hyperspace" it always works with 1 image, but no images are produced if I select 4.

**Comment by bfirsh** [comment]
Thanks for the report! Fixed in #40 and pushing a new version now.
