### ISSUE TITLE
Why Height is limited to 768?

### ISSUE THREAD

**Issue by valentinvieriu** [replicate/cog-stable-diffusion#5]
In the original Implementation height can go to 1024px. Is it possible to adjust his and allow 1024?

<img width="756" alt="image" src="https://user-images.githubusercontent.com/478866/186344147-39c27b30-001c-42b3-bb1a-2fbc11ab8cac.png">

**Comment by andreasjansson** [comment]
@valentinvieriu https://replicate.com/stability-ai/stable-diffusion runs on an A100, and it ran out of memory when width and height were both 1024. I'll see if there's some optimization we can do to allow 1024x1024.

**Comment by valentinvieriu** [comment]
I understand this. I have a 3090 and also seem to run out of memory quite fast, but I'm looking into creating some vertical images, something like Japanese art, and this setting somehow stops me to get
The right aspect ratio. 
The question is why limit the height? If it is allowed why not enable it and let the user decide where he would like to consume his gpu memory, on width or on height
