### ISSUE TITLE
TypeError: unsupported operand type(s) for *: 'FieldInfo' and 'FieldInfo'

### ISSUE THREAD

**Issue by josephcatrambone-crucible** [replicate/cog-stable-diffusion#71]
Update: See [here](https://github.com/replicate/cog-stable-diffusion/issues/71#issuecomment-1380842688) for the stunning conclusion to the saga.

### Cog Info:
$ cog --version
cog version 0.6.1 (built 2022-12-15T20:25:16Z)

### Branch Info:
commit 38510524cf4f3dc679e5945ebb52feb40d52c1a9

### Steps to Reproduce:
1. Clone the cog-stable-diffusion repo.
2. Download the models with the download-models script.
3. Run a build with `cog build -t cog-stable-diffusion`.
4. Hit the /prediction endpoint with a prompt and, optionally, a width. (See  below for sample.)

Sample requests:
```python
requests.post(DIFFUSION_ENDPOINT, json={"prompt": "An oil painting of a sentient potato wearing brilliant silver armor, 4k, high quality, trending", "width": 512, "height": 512, "num_inference_steps": 10})

requests.post(DIFFUSION_ENDPOINT, headers={"content-type": "application/json"}, json={"prompt": "An oil painting of a sentient potato wearing brilliant silver armor, 4k, high quality, trending", "num_inference_steps": 10})
```

### Expected Behavior:
The container will spin for a while and spit back an image based on the prompt.

### Observed Behavior:
The endpoint returns an exception:

```
INFO:     136.24.69.10:63320 - "POST /predictions HTTP/1.1" 200 OK
Using seed: description='Random seed. Leave blank to randomize the seed' extra={'choices': None}
Traceback (most recent call last):
File "/root/.pyenv/versions/3.10.9/lib/python3.10/site-packages/cog/server/worker.py", line 209, in _predict
result = self._predictor.predict(**payload)
File "/root/.pyenv/versions/3.10.9/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
return func(*args, **kwargs)
File "/src/predict.py", line 104, in predict
if width * height > 786432:
TypeError: unsupported operand type(s) for *: 'FieldInfo' and 'FieldInfo'
INFO:     136.24.69.10:63392 - "POST /predictions HTTP/1.1" 200 OK
```

### Reproducibility:
~50% of the time.

The line in the code:
[`https://github.com/replicate/cog-stable-diffusion/blob/main/predict.py#L99`](https://github.com/replicate/cog-stable-diffusion/blob/main/predict.py#L99)
```python
        if width * height > 786432:
            raise ValueError(
                "Maximum size is 1024x768 or 768x1024 pixels, because of memory limits. Please select a lower width or height."
            )
```

This looks completely innocuous.  width and height are both integers and are assigned the value of 'Input', which is a subclass of FieldInfo, according to FastAPI/Pydantic.

**Comment by josephcatrambone-crucible** [comment]
I've attempted to cast the width and height to integers explicitly to see if there's perhaps some type coercion that's getting skipped before the multiply, but then I see, `TypeError: int() argument must be a string, a bytes-like object or a real number, not 'FieldInfo'`.

**Comment by anotherjesse** [comment]
we should probably move this bug to `replicate/cog` with this feedback

**Comment by josephcatrambone-crucible** [comment]
Closing and moving to replicate/cog.
