### ISSUE TITLE
No such file or directory: 'diffusers-cache/models--CompVis--stable-diffusion-safety-checker/snapshots/cb41f3a270d63d454d385fc2e4f571c487c253c5/config.json'

### ISSUE THREAD

**Issue by zeke** [replicate/cog-stable-diffusion#74]
I get this error when running `script/download-weights` on the main branch from a fresh GitHub GPU Codespaces instance:

```
Running 'script/download-weights' in Docker with the current directory mounted as a volume...
Downloading (…)lve/main/config.json: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4.55k/4.55k [00:00<00:00, 4.16MB/s]
Traceback (most recent call last):
  File "/src/script/download-weights", line 19, in <module>
    saftey_checker = StableDiffusionSafetyChecker.from_pretrained(
  File "/root/.pyenv/versions/3.10.10/lib/python3.10/site-packages/transformers/modeling_utils.py", line 2012, in from_pretrained
    config, model_kwargs = cls.config_class.from_pretrained(
  File "/root/.pyenv/versions/3.10.10/lib/python3.10/site-packages/transformers/configuration_utils.py", line 532, in from_pretrained
    config_dict, kwargs = cls.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/root/.pyenv/versions/3.10.10/lib/python3.10/site-packages/transformers/configuration_utils.py", line 559, in get_config_dict
    config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/root/.pyenv/versions/3.10.10/lib/python3.10/site-packages/transformers/configuration_utils.py", line 644, in _get_config_dict
    config_dict = cls._dict_from_json_file(resolved_config_file)
  File "/root/.pyenv/versions/3.10.10/lib/python3.10/site-packages/transformers/configuration_utils.py", line 730, in _dict_from_json_file
    with open(json_file, "r", encoding="utf-8") as reader:
FileNotFoundError: [Errno 2] No such file or directory: 'diffusers-cache/models--CompVis--stable-diffusion-safety-checker/snapshots/cb41f3a270d63d454d385fc2e4f571c487c253c5/config.json'
ⅹ exit status 1
```

cc @replicate/models any ideas?

**Comment by zeke** [comment]
I tried disabling safety checker code but still seeing a similar error:

```
Downloading (…)ain/model_index.json: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 539/539 [00:00<00:00, 543kB/s]
Traceback (most recent call last):
  File "/src/script/download-weights", line 24, in <module>
    pipe = StableDiffusionPipeline.from_pretrained(
  File "/root/.pyenv/versions/3.10.10/lib/python3.10/site-packages/diffusers/pipeline_utils.py", line 459, in from_pretrained
    config_dict = cls.load_config(
  File "/root/.pyenv/versions/3.10.10/lib/python3.10/site-packages/diffusers/configuration_utils.py", line 380, in load_config
    config_dict = cls._dict_from_json_file(config_file)
  File "/root/.pyenv/versions/3.10.10/lib/python3.10/site-packages/diffusers/configuration_utils.py", line 479, in _dict_from_json_file
    with open(json_file, "r", encoding="utf-8") as reader:
FileNotFoundError: [Errno 2] No such file or directory: 'diffusers-cache/models--stabilityai--stable-diffusion-2-1/snapshots/36a01dc742066de2e8c91e7cf0b8f6b53ef53da1/model_index.json'
ⅹ exit status 1
```

**Comment by zeke** [comment]
I see the cached files all greyed out, and some indication that there are symlinks... ?

![Screenshot 2023-03-08 at 1 04 22 PM](https://user-images.githubusercontent.com/2289/223849751-2aa3a194-c227-4e96-a12e-8955f75862e5.png)

**Comment by zeke** [comment]
Getting the same error on a Lambda Labs machine. Looks like something is up with that `config.json` file:

![Screenshot 2023-03-08 at 1 08 08 PM](https://user-images.githubusercontent.com/2289/223850432-0659d26a-e529-46ca-800d-6b8cb667f018.png)

**Comment by daanelson** [comment]
weird! I just ran it from main without issue. perhaps we can figure it out when pairing tomorrow. 

the symlink from `snapshots` to `blobs` is expected, though perhaps a fun surprise.

**Comment by minhchu** [comment]
I'm having same issue but with different model

there is a symlink in `snapshots` but python still throws `FileNotFoundError`

**Comment by chenxwh** [comment]
think it is the issue is from `cache_dir`, here is an alternative way to load and save the model  https://github.com/chenxwh/cog-stable-diffusion/tree/tmp_fix_cachedir

**Comment by daanelson** [comment]
looks like this issue comes from `huggingface_hub` >=0.13, which was released yesterday. Fun! specifying `huggingface-hub==0.12.1` should also fix it.

**Comment by zeke** [comment]
Looks like it's fixed in 0.13.2: https://github.com/huggingface/huggingface_hub/releases/tag/v0.13.2

**Comment by zeke** [comment]
> specifying `huggingface-hub==0.12.1` should also fix it.

How do we do that? `huggingface-hub` is not specified in `cog.yaml`. It's a transitive dependency, presumably of `diffusers`. Does adding it to `build.python_packages` in `cog.yaml` take precedence?

**Comment by chenxwh** [comment]
> How do we do that? `huggingface-hub` is not specified in `cog.yaml`. It's a transitive dependency, presumably of `diffusers`. Does adding it to `build.python_packages` in `cog.yaml` take precedence?

I believe so if you specify `huggingface-hub` after `diffuser` in `cog.yaml`

**Comment by zeke** [comment]
☝🏼 Yep that worked. https://github.com/replicate/cog-stable-diffusion/pull/73/commits/4ef47346605d0b5f4a44f29cf1a3ba6253f17bbe
