### ISSUE TITLE
What is the use of SEED in stability-ai/stable-diffusion?

### ISSUE THREAD

**Issue by chitodi** [replicate/cog-stable-diffusion#78]
[stability-ai/stable-diffusion](https://replicate.com/stability-ai/stable-diffusion) 

And what changes occur because of it?

**Comment by mattt** [comment]
From https://getimg.ai/guides/guide-to-seed-parameter-in-stable-diffusion:

> Seed in Stable Diffusion is a number used to initialize the generation. No need to come up with the number yourself, as it is randomly generated when not specified. But controlling the seed can help you generate reproducible images, experiment with other parameters, or prompt variations.
