### ISSUE TITLE
Sensitive NSFW filter

### ISSUE THREAD

**Issue by maxawzsinger** [replicate/cog-stable-diffusion#84]
trying to build a website allowing people to generate SD images.

based on one of my test prompts 'art by alfredo rodriguez, man in water, dynamic, movement, beautiful oil painting, fine art, award-winning art, beautiful lighting, intricate detail' the replicate api returns an error, with additional info including the following : 'Potential NSFW content was detected in one or more images. A black image will be returned instead. Try again with a different prompt and/or seed.' is there any way to shut off the nsfw filter? otherwise this filter seems too sensitive for everyday use

**Comment by mattt** [comment]
Hi @maxawzsinger. What you're describing is a specific behavior of the Stable Diffusion model. I saw that you also opened https://github.com/replicate/cog-stable-diffusion/issues/84, so I'll close this as a duplicate.
